### ISSUE TITLE
Is't suitable for car classification?

### ISSUE THREAD

**Issue by willard-yuan** [nicklhy/CompCar_Analysis#1]
Hi nicklhy,

I'm really interested in car classification and I found your project here. Recently I have want to classify car by their categories such as bus, car, truck, etc. Is is suitable for car classification using the method?

**Comment by nicklhy** [comment]
你好：
其实github上的只是一些CNN的baseline实验，重要的还是得准备数据以及训练时的调参，你如果要做公交、卡车、小车这样的类型分类，肯定是没问题的，就是一个分类任务。

**Comment by willard-yuan** [comment]
Hi nicklhy,
我大概看了一下CompCar这个数据库，差不多属于精细分类的那种，精细分类的都可以做粗分类也是没问题的。你还在做这块吗？方便加个qq或微信吗，方便请教你问题？

**Comment by nicklhy** [comment]
OK，我现在其实是在做实际场景数据的车辆属性、识别，那个数据集都是网上的图片，只是给我做个参考。
微信、QQ都是553271641

2015-09-04 9:34 GMT+08:00 Yong Yuan notifications@github.com:

**Comment by willard-yuan** [comment]
谢谢~

在 2015年9月4日 上午9:36，nicklhy notifications@github.com写道：
