### ISSUE TITLE
How to call the Reset() in MemoryData by python

### ISSUE THREAD

**Issue by WERush** [nicklhy/CompCar_Analysis#2]
Hi,
    Sorry to bother you, I have a question about the MemoryData layer. When i feed the data into the MemoryData layer by python. There is a warning coming out "MemoryData does not transform array data on Reset()". So do you know how to call the Reset() function by python? Thanks

**Comment by nicklhy** [comment]
@WERush , I think this is a harmless warning.
```
template <typename Dtype>
void MemoryDataLayer<Dtype>::Reset(Dtype* data, Dtype* labels, int n) {
  CHECK(data);
  CHECK(labels);
  CHECK_EQ(n % batch_size_, 0) << "n must be a multiple of batch size";
  // Warn with transformation parameters since a memory array is meant to
  // be generic and no transformations are done with Reset().
  if (this->layer_param_.has_transform_param()) {
    LOG(WARNING) << this->type() << " does not transform array data on Reset()";
  }
  data_ = data;
  labels_ = labels;
  n_ = n;
  pos_ = 0;
}
```
Caffe print this message to let you know that the transform parameters are not used since you are using MemoryDataLayer. You have to transform the raw data image into caffe blobs yourself.

**Comment by WERush** [comment]
@nicklhy , thanks for your quick reply. I get it.
